version: "3.8"

services:
  app:
    build:
      context: ../prototype
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"

  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - "27017:27017"

  sample-api:
    build:
      context: ../sample-api
      dockerfile: Dockerfile
    ports:
       - "8080:8080"
